const $=id=>document.getElementById(id);
const defaults={name:"Pinki",from:"Umesh",date:"23 October",message:"You are one of the most special people in my life. Today is all about celebrating you. 💖",secret:"You are more special than you know.",reasons:"Your smile, your kindness and the way you make people feel loved.",buttonText:"Let's celebrate 🎉",theme:"midnight",accent:"#bd7cff",highlight:"#ff78b7",font:"playfair",language:"en",photos:[],music:"",autoplay:true,hearts:true,confetti:true,gallery:true};
const S={...defaults};
const themes={midnight:["#4b1763","#bd7cff","#ff78b7"],rose:["#5b1835","#ff8fb3","#ffd0df"],ocean:["#123d70","#6db9ff","#9d8cff"],gold:["#5b3c08","#ffd166","#ff9f43"],garden:["#164e3a","#8ee8a4","#ffb6d5"],night:["#3b2a0b","#e9c46a","#fff1b8"]};
const fonts={playfair:"'Playfair Display',serif",poppins:"Poppins,sans-serif",vibes:"'Great Vibes',cursive",pacifico:"Pacifico,cursive"};
let panel=0, page=0;
function esc(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[c]))}
function read(){for(const id of ["name","from","date","message","secret","reasons","buttonText","language","accent","highlight","font"]){S[id]=$(id).value.trim?.()??$(id).value}S.name=S.name||"Birthday Star";S.from=S.from||"Someone special";S.date=S.date||"Today";S.message=S.message||"Happy Birthday! You deserve the most beautiful day. 💖";S.secret=S.secret||"You are more special than you know.";S.reasons=S.reasons||"Your smile, your kindness and the way you make people feel loved.";S.buttonText=S.buttonText||"Let's celebrate 🎉";S.hearts=$("hearts").checked;S.confetti=$("confetti").checked;S.gallery=$("gallery").checked;S.autoplay=$("autoplay").checked}
function applyTheme(){const c=themes[S.theme];document.documentElement.style.setProperty("--bg1",c[0]);document.documentElement.style.setProperty("--a",S.accent||c[1]);document.documentElement.style.setProperty("--b",S.highlight||c[2]);document.documentElement.style.setProperty("--font",fonts[S.font]||fonts.playfair)}
function updateMini(){read();const photo=S.photos[0]?`<img class="miniPhoto" src="${S.photos[0]}" alt="">`:"";$('mini').innerHTML=`<div class="mini"><div class="miniHeart">💖</div><small>${esc(S.date)}</small><h2>Happy Birthday,<br>${esc(S.name)}!</h2><p>${esc(S.message).slice(0,150)}${S.message.length>150?"…":""}</p>${photo}<br><button>${esc(S.buttonText)}</button></div>`;applyTheme()}
function setPanel(n){panel=Math.max(0,Math.min(3,n));document.querySelectorAll('.formstep').forEach(x=>x.classList.toggle('active',+x.dataset.panel===panel));document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===panel))}
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>setPanel(+b.dataset.step));document.querySelectorAll('.next').forEach(b=>b.onclick=()=>setPanel(panel+1));document.querySelectorAll('.backStep').forEach(b=>b.onclick=()=>setPanel(panel-1));
document.querySelectorAll('.theme').forEach(b=>b.onclick=()=>{S.theme=b.dataset.theme;const c=themes[S.theme];$('accent').value=c[1];$('highlight').value=c[2];document.querySelectorAll('.theme').forEach(x=>x.classList.remove('active'));b.classList.add('active');updateMini()});
["name","from","date","message","secret","reasons","buttonText","language","accent","highlight","font"].forEach(id=>$(id).addEventListener('input',updateMini));["hearts","confetti","gallery","autoplay"].forEach(id=>$(id).addEventListener('change',updateMini));
function fileData(f){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)})}
$('photos').onchange=async e=>{S.photos=[];for(const f of [...e.target.files].slice(0,8)){if(f.type.startsWith('image/'))S.photos.push(await fileData(f))}$('thumbs').innerHTML=S.photos.map((x,i)=>`<img class="thumb" src="${x}" alt="Photo ${i+1}">`).join('');$('assets').textContent=`${S.photos.length} photo(s) selected${S.music?' + music ✓':''}`;updateMini()};
$('music').onchange=async e=>{const f=e.target.files[0];if(f){S.music=await fileData(f);$('assets').textContent=`${S.photos.length} photo(s)${S.photos.length?' + ':''}music selected ✓`}};
function saveLocal(){read();localStorage.setItem('birthdaySurpriseV5',JSON.stringify(S));toast('Saved on this device ✓')}
$('save').onclick=saveLocal;
$('share').onclick=async()=>{read();const x={...S,photos:[],music:""};const u=location.href.split('?')[0]+'?surprise='+encodeURIComponent(btoa(unescape(encodeURIComponent(JSON.stringify(x)))));try{await navigator.clipboard.writeText(u);toast('Share link copied ✓')}catch(e){prompt('Copy this link:',u)}};
function downloadBlob(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
async function exportedHTML(){
  read();
  let css='';
  try{css=await fetch('style.css').then(r=>r.text())}catch(e){css='body{margin:0;background:#0b0610;color:#fff;font-family:Arial,sans-serif}.expCard{max-width:720px;margin:8vh auto;padding:35px;border-radius:28px;background:#ffffff12;text-align:center}.btn{border:0;border-radius:999px;padding:12px 18px}.primary{background:linear-gradient(100deg,var(--b),var(--a));color:#fff}.photoGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.photoGrid img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:14px}'}
  const data=btoa(unescape(encodeURIComponent(JSON.stringify(S))));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Happy Birthday ${esc(S.name)} 🎂</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Great+Vibes&family=Playfair+Display:wght@600;700&family=Poppins:wght@400;500;600;700&family=Pacifico&display=swap" rel="stylesheet"><style>${css}</style></head><body><section id="experience"><div class="sky"></div><div id="floaters"></div><button id="closeExp" class="close" onclick="location.reload()">×</button><div id="dots"></div><main id="experienceCard"></main><div class="experienceNav"><button id="prev">←</button><button id="next">→</button></div><audio id="audio" loop></audio></section><script>
const S=JSON.parse(decodeURIComponent(escape(atob('${data}'))));
let page=0;const fonts=${JSON.stringify(fonts)},themes=${JSON.stringify(themes)};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));
function apply(){let c=themes[S.theme]||themes.midnight;document.documentElement.style.setProperty('--bg1',c[0]);document.documentElement.style.setProperty('--a',S.accent||c[1]);document.documentElement.style.setProperty('--b',S.highlight||c[2]);document.documentElement.style.setProperty('--font',fonts[S.font]||fonts.playfair)}
function makeHearts(){if(!S.hearts)return;const b=$('floaters');b.innerHTML='';for(let i=0;i<10;i++){let e=document.createElement('span');e.className='float';e.textContent=['💗','💜','✨','💕'][i%4];e.style.left=(5+Math.random()*90)+'%';e.style.fontSize=(15+Math.random()*18)+'px';e.style.animationDelay=(Math.random()*2)+'s';b.appendChild(e)}}
function render(){apply();const photos=S.gallery&&S.photos?.length?'<div class="photoGrid">'+S.photos.map(x=>'<img src="'+x+'" alt="">').join('')+'</div>':'';const pages=[
'<div class="expCard"><div class="heart">💖</div><small>'+esc(S.date)+'</small><h1>Happy Birthday,<br>'+esc(S.name)+'!</h1><p>'+esc(S.message)+'</p><p>With love,<br><b>'+esc(S.from)+'</b></p><button class="btn primary" onclick="go(1)">'+esc(S.buttonText)+' ✨</button></div>',
'<div class="expCard"><div class="cake">🎂</div><h2>Make a wish, '+esc(S.name)+' ✨</h2><p>Take a deep breath and make one beautiful wish.</p><button class="btn primary" onclick="go(2)">Blow the candles 🎉</button></div>',
'<div class="expCard"><h2>Your memories 📸</h2><p>Little moments that deserve to stay forever.</p>'+(photos||'<p>No photos were added.</p>')+'</div>',
'<div class="expCard paper"><h2>A little letter 💌</h2><p>'+esc(S.message)+'</p><p>I hope this year brings you beautiful memories, peaceful moments, big smiles and everything your heart is wishing for.</p><p>With love,<br><b>'+esc(S.from)+'</b></p><div class="secret">🔐 <b>Secret:</b> '+esc(S.secret)+'</div></div>',
'<div class="expCard final"><div class="heart">🎁</div><h2>One last surprise!</h2><p>'+esc(S.reasons)+'</p><p>Never forget how special you are. ❤️</p><button class="btn primary" onclick="celebrate()">Celebrate! 🎆</button></div>'];
$('experienceCard').innerHTML=pages[page]||pages[0];$('dots').innerHTML=pages.map((_,i)=>'<i class="dot '+(i===page?'on':'')+'"></i>').join('');makeHearts()}
function go(n){page=n;render()}$('next').onclick=()=>{if(page<4){page++;render()}};$('prev').onclick=()=>{if(page>0){page--;render()}};
function celebrate(){if(S.confetti){for(let i=0;i<30;i++){let e=document.createElement('span');e.className='float';e.textContent=['🎉','✨','💖','🎊','⭐'][i%5];e.style.left=Math.random()*100+'%';e.style.animationDuration=(2+Math.random()*3)+'s';$('floaters').appendChild(e)}}}
render();if(S.music&&S.autoplay){document.body.addEventListener('click',()=>$('audio').play().catch(()=>{}),{once:true});$('audio').src=S.music}
</script></body></html>`
}
$('export').onclick=async()=>{toast('Preparing your surprise…');const html=await exportedHTML();downloadBlob(html,'birthday-surprise.html','text/html');toast('Birthday surprise exported ✓')};
$('previewTop').onclick=()=>start();$('make').onclick=()=>start();$('closeExp').onclick=()=>{stopAudio();$('experience').classList.add('hidden');$('studio').classList.remove('hidden');updateMini()};$('next').onclick=()=>{if(page<4){page++;render()}};$('prev').onclick=()=>{if(page>0){page--;render()}};
function start(){read();page=0;$('studio').classList.add('hidden');$('experience').classList.remove('hidden');$('floaters').innerHTML='';if(S.music){$('audio').src=S.music;if(S.autoplay)$('audio').play().catch(()=>{})}render()}
function stopAudio(){$('audio').pause();$('audio').removeAttribute('src');$('audio').load()}
function render(){const photos=S.gallery&&S.photos.length?`<div class="photoGrid">${S.photos.map(x=>`<img src="${x}" alt="">`).join('')}</div>`:'';const pages=[`<div class="expCard"><div class="heart">💖</div><small>${esc(S.date)}</small><h1>Happy Birthday,<br>${esc(S.name)}!</h1><p>${esc(S.message)}</p><p>With love,<br><b>${esc(S.from)}</b></p><button class="btn primary" onclick="goNext()">${esc(S.buttonText)} ✨</button></div>`,`<div class="expCard"><div class="cake">🎂</div><h2>Make a wish, ${esc(S.name)} ✨</h2><p>Take a deep breath and make one beautiful wish.</p><button class="btn primary" onclick="goNext()">Blow the candles 🎉</button></div>`,`<div class="expCard"><h2>Your memories 📸</h2><p>Little moments that deserve to stay forever.</p>${photos||'<p>Make it personal by adding photos in the creator.</p>'}</div>`,`<div class="expCard paper"><h2>A little letter 💌</h2><p>${esc(S.message)}</p><p>I hope this year brings you beautiful memories, peaceful moments, big smiles and everything your heart is wishing for.</p><p>With love,<br><b>${esc(S.from)}</b></p><div class="secret">🔐 <b>Secret:</b> ${esc(S.secret)}</div></div>`,`<div class="expCard final"><div class="heart">🎁</div><h2>One last surprise!</h2><p>${esc(S.reasons)}</p><p>Never forget how special you are. ❤️</p><button class="btn primary" onclick="celebrate()">Celebrate! 🎆</button></div>`];$('experienceCard').innerHTML=pages[page];$('dots').innerHTML=pages.map((_,i)=>`<i class="dot ${i===page?'on':''}"></i>`).join('');if(S.hearts)makeHearts();applyTheme()}
function goNext(){if(page<4){page++;render()}}
function makeHearts(){const box=$('floaters');box.innerHTML='';for(let i=0;i<8;i++){const e=document.createElement('span');e.className='float';e.textContent=['💗','💜','✨','💕'][i%4];e.style.left=(5+Math.random()*90)+'%';e.style.fontSize=(15+Math.random()*18)+'px';e.style.animationDelay=(Math.random()*2)+'s';box.appendChild(e)}}
function celebrate(){if(!S.confetti){toast('Happy Birthday! 🎉');return}for(let i=0;i<32;i++){const e=document.createElement('span');e.className='float';e.textContent=['🎉','✨','💖','🎊','⭐'][i%5];e.style.left=Math.random()*100+'%';e.style.animationDuration=(2+Math.random()*3)+'s';$('floaters').appendChild(e)}toast('Happy Birthday! 🎉💖')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function loadState(x){Object.assign(S,defaults,x||{});for(const id of ['name','from','date','message','secret','reasons','buttonText','language','accent','highlight','font'])if($(id))$(id).value=S[id]??'';['hearts','confetti','gallery','autoplay'].forEach(id=>$(id).checked=!!S[id]);document.querySelectorAll('.theme').forEach(b=>b.classList.toggle('active',b.dataset.theme===S.theme));applyTheme();updateMini()}
function decodeShare(){try{const q=new URLSearchParams(location.search).get('surprise');if(q){const x=JSON.parse(decodeURIComponent(escape(atob(q))));loadState(x);toast('Shared surprise loaded ✓')}}catch(e){console.warn('Share link could not be loaded',e)}}
(function init(){let saved=null;try{saved=JSON.parse(localStorage.getItem('birthdaySurpriseV5'))}catch(e){}loadState(saved||defaults);decodeShare()})();
